### ISSUE TITLE
Support plugins or replicate WinKee [or AutoExec] plugin functionality

### ISSUE THREAD

**Issue by erichiller** [PSKeePass/PoShKeePass#112]
I'm using a setup where there's a single centralized db with a complex master password which resides in a Google drive share. Users with access to the DB use their local windows account to login via a pre-authenticated WinKee configuration per KeePass instance, which essentially unencrypts the local master password with the windows account and logs into the master database with the master password. This would be a wonderful addition.

Maybe a `-rememberMaster` switch when setting up the database connection? [Thus allowing for pure windows account/network login?]

**Comment by jkdba** [comment]
@erichiller I have not looked at WinKee or AutoExec before. I would have to look into it further to fully understand what you would want to accomplish.

From what I get now based on what you said is, winkey allows a user to login to a google drive share and access an encrypted keepass master password using their network login, which then auto authenticates to a keepass database on that share?

Can you further explain how the proposed flag `-rememberMaster` would help? It is just because if it knows where the masterkey is the user does not need to type it? Also, how is the masterkey password encrypted or is just stored in plain text?

**Comment by erichiller** [comment]
Sorry, two separate things there.

WinKee has nothing to do with Google Drive. That is a separate plugin I am using. (If at some point you are able to support direct Google Drive access that would be great too, but not a high priority)

The functionality WinKee offers is:
Uses your Windows Credentials to authenticate you to a database that authenticates via a method other than Windows Credentials.
For example if my database `mydb1.kdbx` requires a master password of `wWBBy00YxfKIwusODl` when I configure the plugin I set it up so that WinKee remembers `wWBBy00YxfKIwusODl` for `mydb1.kdbx`, now I can simply authenticate with my normal windows account.

All I was getting at with the `-rememberMaster` was that this could be the initial switch to configure the binding of the non-windows/network credentials to windows/network credentials.

I hope that made more sense.

**Comment by jkdba** [comment]
@erichiller Yes, it does make more sense. However, I would be concerned with caching the master key password (even as a secure string) as part of the module as an option, it seems rather insecure.

There are two reasons why I don't like this, it forces the module to take responsibility of protecting the users master key password and its outside of the context of this project. The Idea behind this repo is to be a wrapper for the KeePassLib which this functionality is not inherently built in. I think just like the actual KeePass this functionality belongs to in separate script or module that use this module as a base.

I would be happy to help contribute to a separate project or brainstorm ideas of how this might work.
