### ISSUE TITLE
Official Version Support

### ISSUE THREAD

**Issue by mpearon** [PSKeePass/PoShKeePass#130]
Hello!  I'm struggling to get output from any functions provided by PoSHKeePass.

```
Exception calling "Open" with "3" argument(s): "The file version is unsupported.
A newer KeePass version is required to open this file."
```
I'm using KeePass 2.38
Which versions are officially supported?
What would be required to support the latest versions?

**Comment by jkdba** [comment]
Hi @mpearon , I have this outlined in issue #118 this is one of the priority issues and I will look into it making this module support the latest version and if easy then multiple versions.

In the mean time you can try and update the `Import-KPLibrary` function to load the latest dll or keepass.exe. To do this use the `Out-CompressedDll` function found the `bin/EncodeKeePassLib.ps1` file, to generate the embedded dll text and update the  `$EncodedCompressedFile` variable in the` Import-KPLibrary` function with its value.

**Note: Since this is untested and I have no idea what will happen please besure to not run the module against your production keepass database and key file.**

**PLEASE BE SURE TO HAVE BACKUPS OF YOUR DATABASE (.kdbx) and any Key files (.key) before attempting this**

**Comment by jkdba** [comment]
The current version used by the module is 2.34.
