### ISSUE TITLE
Add ShouldProcess to New-*, Remove-* and Update-* cmdlet

### ISSUE THREAD

**Issue by Clebam** [PSKeePass/PoShKeePass#151]
Hi,

Thanks for this project.

I suggest you should use ShouldProcess to most of your commands and set a confirm impact.

For instance : 

`New-KeePassDatabaseConfiguration -DatabaseProfileName $DataBaseProfileName -DatabasePath $DatabasePath -UseMasterKey`

it will overwrite without warning an existing database.
(Well you encourage to backup db, but better not having this db killer around :) )

Thanks again.

**Comment by kwiknick** [comment]
I started adding this functionality this evening.  In case anyone else comes across this issue.

**Comment by jkdba** [comment]
@Clebam Thanks for pointing this out. I agree ShouldProcess should be used but if the `New-KeePassDatabaseConfiguration` is allowing you to overwrite an existing config that is a whole other issue. As it it should be checking to see if a profile with that name exists before it execute. I will definitely look at the code and see what is up.

**Comment by jkdba** [comment]
@Clebam In your example I tested and it will not overwrite existing profile if the same name is specified it will throw an error. If are experiencing otherwise please explain reproduction steps, os version, keepass version, ps version. Also just so we clear what the functions does it just creates a config file entry it does not touch the database `kdbx` file.

I did review the `New-KeePassDatabase` function and found that it should definitely check for existing db first.

All `Update-` and `Remove-`  functions have `ShouldProcess` implemented already, however I could see the value of adding to other commands for discovery and comfort of new users by allowing the -WhatIf command.
