### ISSUE TITLE
Add MasterKey Password as database profile option without key file path

### ISSUE THREAD

**Issue by scautomation** [PSKeePass/PoShKeePass#152]
allow use of Masterkey password without needing KeyPath, which is currently set to required, this is preventing me from using the module as our keepass does not have a key file for access, just master password.
![image](https://user-images.githubusercontent.com/35973682/46749060-9a345f00-cc7a-11e8-9f2a-0250a993aad3.png)

**Comment by jkdba** [comment]
Hi @scautomation thanks for reaching out.

The `-UserMasterKey` parameter is switch parameter when passed it makes a `$true` entry in the config file so the module knows to prompt for a masterkey password/credential (or expect for one to be passed to the module commands) when interacting with the specified database. 

The module does not store your master key in the configuration file as it is unsafe. Below is the correct syntax for what you are trying to achieve. 

`New-KeePassDatabaseConfiguration -DatabaseProfileName 'ray' -DatabasePath 'C:\temp\test\ray.kdbx' -UseMasterKey`

I certainly agree that the error message could be more clear. What is happening when you get this error is that function is "assuming" that the `$pw` value is being passed positionally rather than by explicit parameter name.  In this case the `$pw` value parameter position aligns with the the `-KeyPath` parameter. With out looking at the underlying code and analyzing the error we can also see something is not quite right.

> Cannot validate argument on parameter 'KeyPath'. The "Test-Path $_" validation script for the argument with the value "System.Security.SecureString" did not return a result of True. Determine why the validation script failed, and then try the command again.

1. From here what we can see is that the `-KeyPath` parameter is receiving a value of type `System.Security.SecureString`. Assuming you have good password practices ;) its a safe bet that "$pw" is of that type and it is also highlighted as the issue in the error message stack you shared. 
2. The reason why the error is not saying the data type is not the issue is because the `-KeyPath` parameter is a string and by passing an object of another type its going to see if it can become a string similar to the below. In this instance it the `Test-Path` function (which is the `-Keypath` parameter validation logic) gets the SecureString and attempts to convert to string and see if its a valid/actual path which is not.
```powershell
> $pw = [SecureString]::new()
> $pw.ToString()
System.Security.SecureString
```
